config/routes.rb
Rankasaurus::Application.routes.draw do

  root :to => 'domains#index'

  resources :domains do
    resources :keywords
  end
  

end

app/models/domain.rb
class Domain < ActiveRecord::Base
  has_many :keywords
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  belongs_to :domain
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  def index
    @domains = Domain.all
  end
  
  def show
    @domain = Domain.find(params[:id])
    @keywords = @domain.keywords
  end

  def new
    @domain = Domain.new
  end

  def edit
    @domain = Domain.find(params[:id])
  end

  def create
    @domain = Domain.new(params[:domain])
    if @domain.save
      redirect_to @domain, notice: 'Domain was added successfully.'
    else
      render :action => 'new'
    end
  end

  def update
    @domain = Domain.find(params[:id])

    if @domain.update_attributes(params[:domain])
      redirect_to @domain, notice: 'Domain was saved successfully.'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @domain = Domain.find(params[:id])
    @domain.destroy

    redirect_to domains_url, notice: 'Domain was deleted successfully.'
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController

  def new
    @domain = Domain.find(params[:domain_id])
    @keyword = @domain.keywords.new
  end

  def create
    @domain = Domain.find(params[:domain_id])
    @keyword = @domain.keywords.create(params[:keyword])

    if @keyword.save
      redirect_to @domain, notice: 'Keyword added successfully.'
    else
      render :action => 'new'
    end
  end

  def destroy
    @domain = Domain.find(params[:domain_id])
    @keyword = @domain.keywords.find(params[:id])
    @keyword.destroy

    redirect_to :back, notice: "Keyword deleted successfully."
  end

end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_form.html.haml
= form_for @domain do |f|
  .clearfix
    = f.label :name
    .input
      = f.text_field :name
  .clearfix
    = f.label :url
    .input
      = f.text_field :url
  .actions
    = f.submit "Save", :class => "btn primary"
    = link_to "Cancel", :back, :class => "btn"

app/views/domains/edit.html.haml
%h1 Edit #{@domain.name}

.well
  = link_to "Delete", @domain, :class => "btn", confirm: 'Are you sure?', method: :delete

= render 'form'

app/views/domains/index.html.haml
.page-header
  %h1 Domains

.well
  = link_to "Add domain", new_domain_path, :class => "btn primary"

- unless @domains.nil?
  %table.zebra-striped
    %thead
      %tr
        %th Name
        %th Url
        %th Keywords
        %th Actions
    %tbody
    - @domains.each do |domain|
      %tr
        %td= link_to domain.name, domain_path(domain)
        %td= domain.url
        %td= domain.keywords.count
        %td
          = link_to "View", domain_path(domain), :id => "view_domain_#{domain.id}"
          = link_to "Edit", edit_domain_path(domain), :id => "edit_domain_#{domain.id}"
          = link_to "Delete", domain_path(domain), confirm: "Are you sure you want to delete #{domain.name}?", method: :delete, :id => "delete_domain_#{domain.id}"
- else
  %p Asante Sana! Squash banana! We we nuga! Mi mi apana!

app/views/domains/new.html.haml
%h1 New Domain

= render 'form'

app/views/domains/show.html.haml
.page-header
  %h1
    = @domain.name
    (<a href="#{@domain.url}">#{@domain.url}</a>)
%p
  = link_to "Back to Domains", domains_path, :class => "btn"
  = link_to "Edit this domain", edit_domain_path(@domain), :class => "btn"
%h2 Keywords
%p
  = link_to "New keyword", new_domain_keyword_path(@domain), :class => "btn primary"

- unless @domain.keywords.empty?
  %table.zebra-striped
    %thead
      %tr
        %th Term
        %th Rank
        %th Actions
    %tbody
      - @domain.keywords.each do |keyword|
        %tr
          %td= keyword.term
          %td= keyword.rank
          %td= link_to "Delete", domain_keyword_path(@domain, keyword), confirm: 'Are you sure?', method: :delete, :id => "delete_keyword_#{keyword.id}"

app/views/keywords/new.html.haml
= form_for([@domain, @keyword]) do |f|
  .clearfix
    = f.label :term
    .input
      = f.text_field :term
  .actions
    = f.submit "Save", :class => "btn primary"
    = link_to "Cancel", domain_path(@domain), :class => "btn"
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Rankasaurus
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    
    .topbar
      .fill
        .container
          %a.brand(href="#{root_path}") Rankasaurus
          %ul.nav
            %li= link_to "Home", root_path
            %li= link_to "Domains", domains_path

    .container

      - if flash[:notice]
        .alert-message.success.fade.in(data-alert="alert")
          %a.close(href="#")x
          = notice
      - if flash[:alert]
        .alert-message.error.fade.in(data-alert="alert")
          %a.close(href="#")x
          = alert

      = yield
    
    %footer.footer
      .container
        %p.pull-right
          %a.back-to-top(href="#") Back to top
      

app/views/pages/home.html.haml
Hello